### ISSUE TITLE
upgrade to ember 3.1.4

### ISSUE THREAD

**Issue by officeguy** [aws-samples/aws-mobilehub-ember#5]
just fyi, I've done all the code changes to upgrade this repo to Ember 3.1.4.  let me know if you want a pull request for this or not.

..Marty

**Comment by mlabieniec** [comment]
Hi @officeguy , thank you, yes a PR would be greatly appreciated!

**Comment by officeguy** [comment]
done via https://github.com/aws-samples/aws-mobilehub-ember/pull/6
